// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require, module) {
    var L, LeafletProvider;
    L = require('leaflet');
    LeafletProvider = function() {
      this.map;
      return {
        createMap: function(elementId) {
          this.map = new L.Map(elementId);
          this.addBaseMap();
          return this.map;
        },
        addBaseMap: function() {
          var baseMap;
          baseMap = new L.TileLayer("http://{s}.tiles.mapbox.com/v3/mapbox.mapbox-light/{z}/{x}/{y}.png", {
            attribution: "Map data by MapBox",
            maxZoom: 18
          });
          return this.addLayer(baseMap);
        },
        addLayer: function(layer) {
          return this.map.addLayer(layer);
        },
        setView: function(options) {
          var point;
          point = new L.LatLng(options.lat, options.lon);
          return this.map.setView(point, options.zoomLevel);
        }
      };
    };
    return LeafletProvider;
  });

}).call(this);
