// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    var $, AppRouter, Backbone, LeafletProvider, MapView;
    $ = require('jquery');
    MapView = require('Views/MapView');
    Backbone = require('backbone');
    LeafletProvider = require('MapProviders.Leaflet');
    AppRouter = (function(_super) {

      __extends(AppRouter, _super);

      function AppRouter() {
        return AppRouter.__super__.constructor.apply(this, arguments);
      }

      AppRouter.prototype.routes = {
        "": "BoilerPlate"
      };

      AppRouter.prototype.initialize = function() {
        return this.mapView = new MapView({
          mapProvider: new LeafletProvider()
        });
      };

      return AppRouter;

    })(Backbone.Router);
    return module.exports = {
      AppRouter: AppRouter
    };
  });

}).call(this);
