// Generated by CoffeeScript 1.3.3
(function() {

  define(['Models/ThemeLayer', 'StationData'], function(ThemeLayer, StationData) {
    var plants, symbologyOtions;
    symbologyOtions = [
      {
        range: [1, 2],
        vectorOptions: {
          radius: 5
        }
      }, {
        range: [2, 5],
        vectorOptions: {
          radius: 10
        }
      }, {
        range: [5, 15],
        vectorOptions: {
          radius: 15
        }
      }
    ];
    return plants = new ThemeLayer(StationData.getStations(), {
      property: 'tann',
      symbology: symbologyOtions,
      colorScheme: 'YlOrRd',
      pointToLayer: function(latlng, markerOptions) {
        if (markerOptions) {
          markerOptions.fillOpacity = 0.8;
          markerOptions.stroke = false;
        } else {
          markerOptions = {
            fillOpacity: 0.8,
            radius: 3,
            stroke: false,
            fillColor: 'white'
          };
        }
        return new L.CircleMarker(latlng, markerOptions);
      }
    });
  });

}).call(this);
