// Generated by CoffeeScript 1.3.3
(function() {

  require(['backbone', 'PlantData'], function(Backbone) {
    return Backbone.sync = function(method, model, options) {
      var resp;
      switch (method) {
        case "read":
          return resp = model.id;
      }
    };
  });

}).call(this);
